[package]
name = "magni-jquery"
version = "0.1.0"
authors = ["suozhaoyu <suozhaoyu0530@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1"
regex = "1.3"
lazy_static = "1.4"